### ISSUE TITLE
Can´t install the ADDON

### ISSUE THREAD

**Issue by TheLooking** [martijnberger/pyslapi#33] opened 2019-08-19 08:30 UTC
I see the addon in the prefrences, but i can´t enable it...?

**Comment by dannysetvisions** [comment] 2020-01-30 10:29
same here. 2.81
any news on this?

**Comment by ThoMiCroN** [comment] 2020-02-20 06:48
Even when you change the __init__.py file, it won't be enabled.

**Comment by martijnberger** [comment] 2020-03-08 08:25
This is a known issue. The current released versions i only compatible with 2.79

**Comment by martijnberger** [comment] 2020-03-08 08:28
This is a duplicate of 
Duplicate of #31

**Closed by martijnberger** 2020-03-08 08:28 UTC
